server:
  port: 8080
  servlet:
    context-path: /api # 上下文路径

spring:
  application:
    name: supplychain-basic # 应用名称
  datasource:
    url: jdbc:mysql://localhost:3306/supplychain
    username: root
    password: deesdees
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000
      client-type: lettuce
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.hust.cse.supplychain.basic.modules.*.entity,org.hust.cse.supplychain.basic.modules.*.model.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启SQL日志

jwt:
  secret: your-secret-key-should-be-very-long-and-secure
  expiration: 86400 # 24小时

logging:
  level:
    org.springframework.security: DEBUG
    org.hust.cse.supplychain.basic: DEBUG

# 文件上传配置
file:
  upload:
    path: ${user.home}/supplychain/upload  # 文件上传路径
  access:
    url: http://localhost:8080/api/files   # 文件访问URL前缀

